# Generated by Django 5.2.6 on 2025-10-10 13:23

import audio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualpayment',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='qr_code',
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='original_file',
            field=models.FileField(upload_to=audio.models.user_audio_path),
        ),
        migrations.AlterField(
            model_name='outputfile',
            name='file',
            field=models.FileField(upload_to=audio.models.user_output_path),
        ),
    ]
